[about]
name = "Elias Lundell"
position = ["Student @ KTH", "Research Assistant @ KTH", "Metaverse Developer @ Around the Corner"]
text = """I'm Elias Lundell, currently pursuing my studies in Engineering Mathematics at the Royal Institute of Technology (KTH) in Stockholm. 
My journey in academia began with a strong foundation in mathematics and natural sciences during my time at Norra Reals Gymnasium, where I specialized in Mathematics.
I have competed in the Swedish Programming- and Mathematics Olympiads and works as a teacher at <a href="https://mattekollo.se">Mattekollo</a> where I teach aspiring students.

<br>
<br>

In addition to my formal education, I actively engage in research and practical projects.
Currently, I serve as a Research Assistant in the CHAINS research group at KTH where I help perform studies on security in Software Supply Chains.
At Around the Corner, I leverage my skills to enhance social VR platforms such as Mozilla Hubs and AltspaceVR. 
From integrating interactive elements like quizzes and online polls to creating digital twins that display real-time data from IoT devices, I'm passionate about making real and fun social interactions digitally.

<br>
<br>

I also enjoy performing arts, during elementary school I went to Täby Musikklasser, where I sang in a choir and had mulitple performances each year. 
I'm now, outside of my studies, highly active in Fysikalen and Kårspexet, two musical-theatre organizations at KTH. 

<br>
<br>

Looking ahead, I'm excited to continue my journey of learning and exploration, driven by a passion for software development, technology, and innovation.
"""

[[resume.education]]
title = "Royal Institute of Technology (KTH), Sweden"
time = "2022 - Present"
description = "Currently studying Engineering Mathematics at KTH in Stockholm."

[[resume.education]]
title = "Mattekollo (Summer Math Camp)"
time = "Summers of 2016 - 2021"
description = 'I participated at <a href="https://mattekollo.se">Mattekollo</a> as a pupil each summer during 2016 to 2019. Mattekollo gathers extra interested students for 10 days of intensive learning and social exchange.'

[[resume.education]]
title = "Norra Real"
time = "2019 - 2022"
description = "Studied Natural Sciences, Mathematics speciallization, at Norra Reals Gymnasium in Stockholm."

[[resume.education]]
title = "Täby Musikklasser"
time = "2013 - 2019"
description = "In addition to the normal elementary education I went to a music class at Näsbydalskolan in Täby. Singing in a choir every day, large performances multiple times every year."

[[resume.experience]]
title = "Undergraduate Assistant"
time = "2024 - Present"
description = 'Working as Research Assistant in the <a href="https://chains.proj.kth.se">CHAINS</a> research group at KTH.'

[[resume.experience]]
title = "Leader at Mattekollo (Summer Math Camp)"
time = "Summers of 2022 - Present"
description = 'After becoming to old to participate as a pupil at <a href="https://mattekollo.se">Mattekollo</a>, I imediatelly started as a teacher, focusing on programming. The work consist both of creating lessons combined with responsibility for the pupils.'

[[resume.experience]]
title = "Metaverse Developer"
time = "2021 - Present"
description = """Working at <a href="https://aroundthecorner.se">Around the Corner</a>. 
I add interactivity and tools to social VR platforms such as Mozilla Hubs and AltspaceVR. 
Examples of what I've added includes quizzes, online polls, enhancing presentations with audio and visual effects within the metaverse, as well as digitals twins showing real time data from IoT devices.
This has been done using the respective platforms API aswell as modifying the client when possible."""

[[resume.experience]]
title = "Supplementary Instructions Leader"
time = "Fall of 2023"
description = "Worked as group leader for Supplementary Instruction sessions in the courses SF1672 Linear algebra and SF1673 Analysis in one variable at KTH."

[[resume.experience]]
title = "Analysis and Database Programmer"
time = "Summers of 2020 - 2023"
description = """Worked at the <a href="https://nrm.se">Swedish Museum of Natural History</a>.
I have worked during the summers to build tools for automatic workflows and to categorize data using R and shiny."""

[[resume.experience]]
title = "Sailing Instructor"
time = "2019 - 2021"
description = """Worked at Trälhavets Båtklub, TBK, as a sailing instructor both on weekly practice sessions and during summer camps. 
In 2021 I was head instructor for weekly practice sessions."""

[[resume.volunteering]]
title = "Student Social Activities"
time = "2022 - 2024"
description = """2024 Secretary (Borad member) in the Physics Chapter
<br>
2023 - 2024 Directeur (President) of Kårspexet
<br>
2022 - 2023 President of Fysikalen, the Physics Chapter's spex
<br>
2022 - 2024 Mattermästare, responsible for the Physics Chapter communication plattform <a href="https://mattermost.se">mattermost.se</a>."""

[[projects]]
title = "Diploma Project (Gymnasium): Effects of Population Size on Food-collecting Efficiency in Simulated Swarms of Pheromone-guided Robots"
description = """A simulation of ants/agents following each other's pheromones. 
We then test how the number of ants/agents affects their ability to pickup food and bring it home to their nest. 
The base is highly inspired by Sebastian Lague's video "Code Adventures: Ant and Slime Simulations". 
All simulation is done in a compute shader enabling a very high number of agents."""
link = "https://github.com/logflames/ant-simulation"
img = "./assets/images/ants-1.jpg"
img-alt = "Ants"
tags = ["C++"]

[[projects]]
title = "Snabba Schemat: A schedule proxy to load and cache schedules"
description = """A schedule proxy, both back- and frontend, which loads and cashes a schedule from Skola24.
This was created due to Stockholm "Skolplattformen"'s incredibly stupid and long login process.
Snabba Schemat saves the login in cookies and cashes it on the server, giving instant access as well as an export to .ical to add to google calendar."""
link = "https://github.com/logflames/snabba-schemat"
img = "./assets/images/snabba-schemat-1.jpg"
img-alt = "A schedule in darkmode"
tags = ["Web", "Typescript"]

[[projects]]
title = "Games made for Ludum Dare"
description = """Ludum Dare is a game-making competition where you create a game, entirely from scratch, in 48h.
My entries are all (so far) made in Unity, and all but the first two were made together with a 3d-Designer friend."""
link = "https://ldjam.com/users/logflames/games"
img = "./assets/images/ldjam-1.jpg"
img-alt = "The logo of Ludum Dare, a game making competition."
tags = ["Game", "Unity"]

[[projects]]
title = "Mattermost Bots for the Physics Chapter"
description = """The Physics Chapter uses the open source communication platform Mattermost. 
To expand usability I have written a number of bots for this. 
These bots do everything from countdown to big events, adding new users to the correct default channels, adding chapter members to specific course-channels based on a data-extract from ladok, provide eastereggs such as the head of the reception is allways online.
The bots also provide biggger functionality such as allowing real-time translation of any message using GPT 3.5 and uploading posts to the Physics Chapter website from a mattermost message."""
link = "https://github.com/logflames/mattermost-bots/"
img = "./assets/images/mattermost-bots-1.jpg"
img-alt = "The mattermost logo with -bots written under it."
tags = ["Python"]

[[projects]]
title = "Genotype Check: Matching bear DNA to group samples into individuals"
description = """A R package and Shiny app that loads sequenced bear DNA and categorizes new data against a database of already known individuals. Including easy of use features such as a map, easily sorting the non-problematic individuals and easy to manually review edge-cases."""
link = "https://github.com/CGI-NRM/GenotypeCheck"
img = "./assets/images/genotype-check-1.jpg"
img-alt = "DNA helix"
tags = ["R"]

[[projects]]
title = "Follow Spot"
description = """A python program that takes in a camera stream of a stage and converts the mouse position to pan/tilt instructions for a moving head fixture."""
link = "https://github.com/logflames/folje"
img = "./assets/images/folje-1.jpg"
img-alt = "A virtual follow spot shining on a model of a person"
tags = ["Python"]

[[posters]]
title = "SF1693 Partiential Differential Equations - Vibrations of a drumhead"
description = "A project to explore analytical and numerical methods of a vibrating drumhead modelled as a vibrating membrane fastened around the border."
pdf = "./assets/posters/SF1693 PDE Project.pdf"
img = "./assets/posters/SF1693 PDE Project.jpg"
img-alt = ""

[[posters]]
title = "Fractureiser: Attack on Minecraft Mods"
description = "An explanation of the Fractureiser virus spread in the minecraft modding scene in 2023. Created for the 3rd KTH Workshop on the Software Supply Chain poster session."
pdf = "./assets/posters/CHAINS Fractureiser.pdf"
img = "./assets/posters/CHAINS Fractureiser.jpg"
img-alt = ""

[[posters]]
title = "SF1672 Linear Algebra - Markov Chains"
description = "A project within the corse SF1672 Linear Algebra, we created a Markov Chain that is trained on all songs in the Physics Chapter's song book, and which can then create novel (albeit not very great) songs from a seed-word."
pdf = "./assets/posters/LinAlg Markov Poster.pdf"
img = "./assets/posters/LinAlg Markov Poster.jpg"
img-alt = ""
